Project network layer
arnekuchenbecker/kitchen-planer-app pull request #203
Opened 2024-09-23 14:56 UTC by arnekuchenbecker

2024-10-08 12:06 UTC, kittyahy reviewed
When talking about an ID it's the offline Id, isn't  it?

2024-10-08 15:37 UTC, kittyahy requested changes
is there a possibility to test it? Or could you write a test?

2024-11-20 14:02 UTC, arnekuchenbecker commented on app/src/main/java/com/scouts/kitchenplaner/networklayer/kitchenplaner/dtos/projects/ServerAllergenPeopleDTO.kt
> + * @param arrivalDate The date the person arrives
While that is true in principle,

1. From a kitchen perspective it really doesn't matter
2. Everywhere else we also wrote it this way, so for consistencies sake I would leave it like this

2024-11-20 14:16 UTC, arnekuchenbecker commented on app/src/main/java/com/scouts/kitchenplaner/networklayer/ModelConversion.kt
> +fun Project.toNetworkLayerDTO(onlineID: Long): ServerProjectDTO {
Fixed. I think I wrote this function before I was done with changing the ```Project``` class, which is also why there is no unit conversions and number changes being passed into this method. I created two issues to fix these (#204 and #205), as the unit conversions depend on that PR (#189) and the number changes require some thinking into how we represent those on both the server and the app as it is currently not elegantly possible to extract them from a project.

2024-11-20 14:18 UTC, arnekuchenbecker commented
> When talking about an ID it's the offline Id, isn't it?

Depends on where you are, but usually in the app that is correct, yes

2024-11-20 14:22 UTC, arnekuchenbecker commented
> is there a possibility to test it? Or could you write a test?

What exactly do you want to have tested? There is definitely the possibility to write tests for Retrofit API (I think I already did that for the Chefkoch stuff so it wouldn't be too difficult either), but I find it difficult to judge what functionality actually needs tests tbh. I think it would make sense to write at least an integration test once the model conversion for unit conversions (#204) and PersonNumberChanges (#205) are in, otherwise these test have to change once these issues are done.

2024-12-03 10:09 UTC, kittyahy approved these changes

2024-12-03 11:16 UTC, merged