Project overview data layer
arnekuchenbecker/kitchen-planer-app pull request #54
Opened 2024-01-08 10:36 UTC by arnekuchenbecker

2024-01-09 11:28 UTC, kittyahy requested changes

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/daos/AllergenDAO.kt
> + * Copyright (C) 2023  Arne Kuchenbecker, Antonia Heiming
Update Licence

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/entities/PersonNumberChangeEntity.kt
> + * Copyright (C) 2023  Arne Kuchenbecker, Antonia Heiming
Change Licence

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/entities/RecipeProjectMealEntity.kt
> + * Copyright (C) 2023  Arne Kuchenbecker, Antonia Heiming
Change Licence

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/exceptions/DuplicatePrimaryKeyException.kt
> + * Copyright (C) 2023  Arne Kuchenbecker, Antonia Heiming
Change Licence

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/daos/RecipeManagementDAO.kt
> + * Copyright (C) 2023  Arne Kuchenbecker, Antonia Heiming
Change Licence

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/entities/RecipeProjectMealEntity.kt
> +        ForeignKey(
Change to TODO

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/repositories/ProjectRepository.kt
>      fun getAllProjectsOverview() : Flow<List<ProjectStub>> {
Only for testing purposes

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/repositories/ProjectRepository.kt
How to:
- add alternative recipe
- add picture
- change number of people
-change allergen persons
- get recipes for a project (to analyze the allergens)

2024-01-09 11:28 UTC, kittyahy commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/ModelConversion.kt
> +    personNumbers: List<PersonNumberChangeEntity>
Unused

2024-01-09 11:37 UTC, arnekuchenbecker commented on app/src/main/java/com/scouts/kitchenplaner/datalayer/repositories/ProjectRepository.kt
Recipe related stuff should be done once recipes are available

2024-01-10 16:00 UTC, kittyahy approved these changes

2024-01-10 16:01 UTC, merged